// Package advisories provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package advisories

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Advisory defines model for Advisory.
type Advisory struct {
	// ApiUrl API URL for this advisory
	ApiUrl         *string  `json:"api_url,omitempty"`
	BlastRadius    *float32 `json:"blast_radius,omitempty"`
	Classification *string  `json:"classification,omitempty"`
	CreatedAt      *string  `json:"created_at,omitempty"`
	CvssScore      *float32 `json:"cvss_score,omitempty"`
	CvssVector     *string  `json:"cvss_vector,omitempty"`
	Description    *string  `json:"description,omitempty"`
	EpssPercentage *float32 `json:"epss_percentage,omitempty"`
	EpssPercentile *float32 `json:"epss_percentile,omitempty"`

	// HtmlUrl HTML URL for this advisory
	HtmlUrl     *string               `json:"html_url,omitempty"`
	Identifiers *[]string             `json:"identifiers,omitempty"`
	Origin      *string               `json:"origin,omitempty"`
	Packages    *[]PackageWithDetails `json:"packages,omitempty"`
	PublishedAt *string               `json:"published_at,omitempty"`
	References  *[]string             `json:"references,omitempty"`

	// RelatedAdvisories Advisories from other sources for the same vulnerability (matched by CVE)
	RelatedAdvisories *[]RelatedAdvisory `json:"related_advisories,omitempty"`
	RepositoryUrl     *string            `json:"repository_url,omitempty"`
	Severity          *string            `json:"severity,omitempty"`
	SourceKind        *string            `json:"source_kind,omitempty"`
	Title             *string            `json:"title,omitempty"`
	UpdatedAt         *string            `json:"updated_at,omitempty"`
	Url               *string            `json:"url,omitempty"`
	Uuid              *string            `json:"uuid,omitempty"`
	WithdrawnAt       *string            `json:"withdrawn_at,omitempty"`
}

// Package defines model for Package.
type Package struct {
	Ecosystem   *string `json:"ecosystem,omitempty"`
	PackageName *string `json:"package_name,omitempty"`
}

// PackageWithDetails defines model for PackageWithDetails.
type PackageWithDetails struct {
	AffectedVersions *[]string `json:"affected_versions,omitempty"`
	Ecosystem        *string   `json:"ecosystem,omitempty"`
	PackageName      *string   `json:"package_name,omitempty"`

	// Purl Package URL (PURL) for this package
	Purl       *string `json:"purl,omitempty"`
	Statistics *struct {
		DependentPackagesCount *int    `json:"dependent_packages_count,omitempty"`
		DependentReposCount    *int    `json:"dependent_repos_count,omitempty"`
		Downloads              *int    `json:"downloads,omitempty"`
		DownloadsPeriod        *string `json:"downloads_period,omitempty"`
	} `json:"statistics,omitempty"`
	UnaffectedVersions *[]string `json:"unaffected_versions,omitempty"`
	Versions           *[]struct {
		FirstPatchedVersion    *string `json:"first_patched_version,omitempty"`
		VulnerableVersionRange *string `json:"vulnerable_version_range,omitempty"`
	} `json:"versions,omitempty"`
}

// RelatedAdvisory defines model for RelatedAdvisory.
type RelatedAdvisory struct {
	SourceKind *string `json:"source_kind,omitempty"`
	Url        *string `json:"url,omitempty"`
	Uuid       *string `json:"uuid,omitempty"`
}

// Source defines model for Source.
type Source struct {
	AdvisoriesCount *int    `json:"advisories_count,omitempty"`
	CreatedAt       *string `json:"created_at,omitempty"`
	Id              *int    `json:"id,omitempty"`
	Kind            *string `json:"kind,omitempty"`
	Name            *string `json:"name,omitempty"`
	UpdatedAt       *string `json:"updated_at,omitempty"`
	Url             *string `json:"url,omitempty"`
}

// GetAdvisoriesParams defines parameters for GetAdvisories.
type GetAdvisoriesParams struct {
	// Ecosystem Ecosystem to filter by
	Ecosystem *string `form:"ecosystem,omitempty" json:"ecosystem,omitempty"`

	// PackageName Package to filter by
	PackageName *string `form:"package_name,omitempty" json:"package_name,omitempty"`

	// Severity Severity to filter by
	Severity *string `form:"severity,omitempty" json:"severity,omitempty"`

	// RepositoryUrl Repository URL to filter by
	RepositoryUrl *string `form:"repository_url,omitempty" json:"repository_url,omitempty"`

	// Source Source to filter by (e.g. github, erlef, cpansa)
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// LookupAdvisoriesParams defines parameters for LookupAdvisories.
type LookupAdvisoriesParams struct {
	// Purl Package URL (PURL) to lookup advisories for. Format: pkg:type/namespace/name@version
	Purl *string `form:"purl,omitempty" json:"purl,omitempty"`

	// RepositoryUrl Source repository URL to lookup advisories for
	RepositoryUrl *string `form:"repository_url,omitempty" json:"repository_url,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdvisories request
	GetAdvisories(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupAdvisories request
	LookupAdvisories(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdvisoriesPackages request
	GetAdvisoriesPackages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdvisory request
	GetAdvisory(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSources request
	GetSources(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSource request
	GetSource(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdvisories(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LookupAdvisories(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupAdvisoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdvisoriesPackages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoriesPackagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdvisory(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoryRequest(c.Server, advisoryUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSources(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourcesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSource(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, sourceKind)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdvisoriesRequest generates requests for GetAdvisories
func NewGetAdvisoriesRequest(server string, params *GetAdvisoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Ecosystem != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ecosystem", runtime.ParamLocationQuery, *params.Ecosystem); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PackageName != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "package_name", runtime.ParamLocationQuery, *params.PackageName); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Severity != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "severity", runtime.ParamLocationQuery, *params.Severity); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RepositoryUrl != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "repository_url", runtime.ParamLocationQuery, *params.RepositoryUrl); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Source != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "source", runtime.ParamLocationQuery, *params.Source); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created_after", runtime.ParamLocationQuery, *params.CreatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "updated_after", runtime.ParamLocationQuery, *params.UpdatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupAdvisoriesRequest generates requests for LookupAdvisories
func NewLookupAdvisoriesRequest(server string, params *LookupAdvisoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/lookup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Purl != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "purl", runtime.ParamLocationQuery, *params.Purl); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RepositoryUrl != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "repository_url", runtime.ParamLocationQuery, *params.RepositoryUrl); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdvisoriesPackagesRequest generates requests for GetAdvisoriesPackages
func NewGetAdvisoriesPackagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/packages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdvisoryRequest generates requests for GetAdvisory
func NewGetAdvisoryRequest(server string, advisoryUUID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "advisoryUUID", runtime.ParamLocationPath, advisoryUUID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourcesRequest generates requests for GetSources
func NewGetSourcesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourceRequest generates requests for GetSource
func NewGetSourceRequest(server string, sourceKind string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sourceKind", runtime.ParamLocationPath, sourceKind)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdvisoriesWithResponse request
	GetAdvisoriesWithResponse(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*GetAdvisoriesResponse, error)

	// LookupAdvisoriesWithResponse request
	LookupAdvisoriesWithResponse(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*LookupAdvisoriesResponse, error)

	// GetAdvisoriesPackagesWithResponse request
	GetAdvisoriesPackagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdvisoriesPackagesResponse, error)

	// GetAdvisoryWithResponse request
	GetAdvisoryWithResponse(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*GetAdvisoryResponse, error)

	// GetSourcesWithResponse request
	GetSourcesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcesResponse, error)

	// GetSourceWithResponse request
	GetSourceWithResponse(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)
}

type GetAdvisoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Advisory
}

// Status returns HTTPResponse.Status
func (r GetAdvisoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LookupAdvisoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Advisory
	JSON400      *struct {
		Error *string `json:"error,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r LookupAdvisoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupAdvisoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdvisoriesPackagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Package
}

// Status returns HTTPResponse.Status
func (r GetAdvisoriesPackagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoriesPackagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdvisoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Advisory
}

// Status returns HTTPResponse.Status
func (r GetAdvisoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourcesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Source
}

// Status returns HTTPResponse.Status
func (r GetSourcesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourcesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAdvisoriesWithResponse request returning *GetAdvisoriesResponse
func (c *ClientWithResponses) GetAdvisoriesWithResponse(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*GetAdvisoriesResponse, error) {
	rsp, err := c.GetAdvisories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoriesResponse(rsp)
}

// LookupAdvisoriesWithResponse request returning *LookupAdvisoriesResponse
func (c *ClientWithResponses) LookupAdvisoriesWithResponse(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*LookupAdvisoriesResponse, error) {
	rsp, err := c.LookupAdvisories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupAdvisoriesResponse(rsp)
}

// GetAdvisoriesPackagesWithResponse request returning *GetAdvisoriesPackagesResponse
func (c *ClientWithResponses) GetAdvisoriesPackagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdvisoriesPackagesResponse, error) {
	rsp, err := c.GetAdvisoriesPackages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoriesPackagesResponse(rsp)
}

// GetAdvisoryWithResponse request returning *GetAdvisoryResponse
func (c *ClientWithResponses) GetAdvisoryWithResponse(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*GetAdvisoryResponse, error) {
	rsp, err := c.GetAdvisory(ctx, advisoryUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoryResponse(rsp)
}

// GetSourcesWithResponse request returning *GetSourcesResponse
func (c *ClientWithResponses) GetSourcesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcesResponse, error) {
	rsp, err := c.GetSources(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourcesResponse(rsp)
}

// GetSourceWithResponse request returning *GetSourceResponse
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, sourceKind, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// ParseGetAdvisoriesResponse parses an HTTP response from a GetAdvisoriesWithResponse call
func ParseGetAdvisoriesResponse(rsp *http.Response) (*GetAdvisoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLookupAdvisoriesResponse parses an HTTP response from a LookupAdvisoriesWithResponse call
func ParseLookupAdvisoriesResponse(rsp *http.Response) (*LookupAdvisoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupAdvisoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error *string `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetAdvisoriesPackagesResponse parses an HTTP response from a GetAdvisoriesPackagesWithResponse call
func ParseGetAdvisoriesPackagesResponse(rsp *http.Response) (*GetAdvisoriesPackagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoriesPackagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Package
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAdvisoryResponse parses an HTTP response from a GetAdvisoryWithResponse call
func ParseGetAdvisoryResponse(rsp *http.Response) (*GetAdvisoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSourcesResponse parses an HTTP response from a GetSourcesWithResponse call
func ParseGetSourcesResponse(rsp *http.Response) (*GetSourcesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourcesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
