// Package advisories provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package advisories

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Advisory defines model for Advisory.
type Advisory struct {
	// ApiUrl API URL for this advisory
	ApiUrl         *string  `json:"api_url,omitempty"`
	BlastRadius    *float32 `json:"blast_radius,omitempty"`
	Classification *string  `json:"classification,omitempty"`
	CreatedAt      *string  `json:"created_at,omitempty"`
	CvssScore      *float32 `json:"cvss_score,omitempty"`
	CvssVector     *string  `json:"cvss_vector,omitempty"`
	Description    *string  `json:"description,omitempty"`
	EpssPercentage *float32 `json:"epss_percentage,omitempty"`
	EpssPercentile *float32 `json:"epss_percentile,omitempty"`

	// HtmlUrl HTML URL for this advisory
	HtmlUrl     *string               `json:"html_url,omitempty"`
	Identifiers *[]string             `json:"identifiers,omitempty"`
	Origin      *string               `json:"origin,omitempty"`
	Packages    *[]PackageWithDetails `json:"packages,omitempty"`
	PublishedAt *string               `json:"published_at,omitempty"`
	References  *[]string             `json:"references,omitempty"`

	// RelatedAdvisories Advisories from other sources for the same vulnerability (matched by CVE)
	RelatedAdvisories *[]RelatedAdvisory `json:"related_advisories,omitempty"`
	RepositoryUrl     *string            `json:"repository_url,omitempty"`
	Severity          *string            `json:"severity,omitempty"`
	SourceKind        *string            `json:"source_kind,omitempty"`
	Title             *string            `json:"title,omitempty"`
	UpdatedAt         *string            `json:"updated_at,omitempty"`
	Url               *string            `json:"url,omitempty"`
	Uuid              *string            `json:"uuid,omitempty"`
	WithdrawnAt       *string            `json:"withdrawn_at,omitempty"`
}

// Package defines model for Package.
type Package struct {
	Ecosystem   *string `json:"ecosystem,omitempty"`
	PackageName *string `json:"package_name,omitempty"`
}

// PackageWithDetails defines model for PackageWithDetails.
type PackageWithDetails struct {
	AffectedVersions *[]string `json:"affected_versions,omitempty"`
	Ecosystem        *string   `json:"ecosystem,omitempty"`
	PackageName      *string   `json:"package_name,omitempty"`

	// Purl Package URL (PURL) for this package
	//
	// Example: pkg:npm/lodash
	Purl               *string                        `json:"purl,omitempty"`
	Statistics         *PackageWithDetails_Statistics `json:"statistics,omitempty"`
	UnaffectedVersions *[]string                      `json:"unaffected_versions,omitempty"`
	Versions           *[]PackageWithDetails_Versions `json:"versions,omitempty"`
}

// PackageWithDetails_Statistics defines model for PackageWithDetails.Statistics.
type PackageWithDetails_Statistics struct {
	DependentPackagesCount *int    `json:"dependent_packages_count,omitempty"`
	DependentReposCount    *int    `json:"dependent_repos_count,omitempty"`
	Downloads              *int    `json:"downloads,omitempty"`
	DownloadsPeriod        *string `json:"downloads_period,omitempty"`
}

// PackageWithDetails_Versions defines model for PackageWithDetails.Versions.
type PackageWithDetails_Versions struct {
	FirstPatchedVersion    *string `json:"first_patched_version,omitempty"`
	VulnerableVersionRange *string `json:"vulnerable_version_range,omitempty"`
}

// RelatedAdvisory defines model for RelatedAdvisory.
type RelatedAdvisory struct {
	SourceKind *string `json:"source_kind,omitempty"`
	Url        *string `json:"url,omitempty"`
	Uuid       *string `json:"uuid,omitempty"`
}

// Source defines model for Source.
type Source struct {
	AdvisoriesCount *int    `json:"advisories_count,omitempty"`
	CreatedAt       *string `json:"created_at,omitempty"`
	Id              *int    `json:"id,omitempty"`
	Kind            *string `json:"kind,omitempty"`
	Name            *string `json:"name,omitempty"`
	UpdatedAt       *string `json:"updated_at,omitempty"`
	Url             *string `json:"url,omitempty"`
}

// GetAdvisoriesParams defines parameters for GetAdvisories.
type GetAdvisoriesParams struct {
	// Ecosystem Ecosystem to filter by
	Ecosystem *string `form:"ecosystem,omitempty" json:"ecosystem,omitempty"`

	// PackageName Package to filter by
	PackageName *string `form:"package_name,omitempty" json:"package_name,omitempty"`

	// Severity Severity to filter by
	Severity *string `form:"severity,omitempty" json:"severity,omitempty"`

	// RepositoryUrl Repository URL to filter by
	RepositoryUrl *string `form:"repository_url,omitempty" json:"repository_url,omitempty"`

	// Source Source to filter by (e.g. github, erlef, cpansa)
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// LookupAdvisoriesParams defines parameters for LookupAdvisories.
type LookupAdvisoriesParams struct {
	// Purl Package URL (PURL) to lookup advisories for. Format: pkg:type/namespace/name@version
	Purl *string `form:"purl,omitempty" json:"purl,omitempty"`

	// RepositoryUrl Source repository URL to lookup advisories for
	RepositoryUrl *string `form:"repository_url,omitempty" json:"repository_url,omitempty"`
}

// LookupAdvisories400JSONResponseBody defines parameters for LookupAdvisories.
type LookupAdvisories400JSONResponseBody struct {
	// Error Example: purl or repository_url parameter is required
	Error *string `json:"error,omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetAdvisories list advisories
	//
	// Corresponds with GET /advisories (the `GetAdvisories` operationId).
	GetAdvisories(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupAdvisories lookup advisories by Package URL (PURL) or repository URL
	//
	// Lookup security advisories for a package using Package URL (PURL) specification or by source repository URL. One of purl or repository_url must be provided. Results are deduplicated by CVE identifier.
	//
	// Corresponds with GET /advisories/lookup (the `LookupAdvisories` operationId).
	LookupAdvisories(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdvisoriesPackages list packages that have advisories
	//
	// Corresponds with GET /advisories/packages (the `GetAdvisoriesPackages` operationId).
	GetAdvisoriesPackages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdvisory get an advisory by uuid
	//
	// Corresponds with GET /advisories/{advisoryUUID} (the `GetAdvisory` operationId).
	GetAdvisory(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSources list advisory sources
	//
	// Corresponds with GET /sources (the `GetSources` operationId).
	GetSources(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSource get a source by kind
	//
	// Corresponds with GET /sources/{sourceKind} (the `GetSource` operationId).
	GetSource(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetAdvisories list advisories
//
// Corresponds with GET /advisories (the `GetAdvisories` operationId).
func (c *Client) GetAdvisories(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupAdvisories lookup advisories by Package URL (PURL) or repository URL
//
// Lookup security advisories for a package using Package URL (PURL) specification or by source repository URL. One of purl or repository_url must be provided. Results are deduplicated by CVE identifier.
//
// Corresponds with GET /advisories/lookup (the `LookupAdvisories` operationId).
func (c *Client) LookupAdvisories(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupAdvisoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAdvisoriesPackages list packages that have advisories
//
// Corresponds with GET /advisories/packages (the `GetAdvisoriesPackages` operationId).
func (c *Client) GetAdvisoriesPackages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoriesPackagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAdvisory get an advisory by uuid
//
// Corresponds with GET /advisories/{advisoryUUID} (the `GetAdvisory` operationId).
func (c *Client) GetAdvisory(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdvisoryRequest(c.Server, advisoryUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSources list advisory sources
//
// Corresponds with GET /sources (the `GetSources` operationId).
func (c *Client) GetSources(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourcesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSource get a source by kind
//
// Corresponds with GET /sources/{sourceKind} (the `GetSource` operationId).
func (c *Client) GetSource(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, sourceKind)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdvisoriesRequest constructs an http.Request for the GetAdvisories method
func NewGetAdvisoriesRequest(server string, params *GetAdvisoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Ecosystem != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ecosystem", *params.Ecosystem, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PackageName != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "package_name", *params.PackageName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Severity != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "severity", *params.Severity, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.RepositoryUrl != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "repository_url", *params.RepositoryUrl, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Source != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "source", *params.Source, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_after", *params.CreatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "updated_after", *params.UpdatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "order", *params.Order, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupAdvisoriesRequest constructs an http.Request for the LookupAdvisories method
func NewLookupAdvisoriesRequest(server string, params *LookupAdvisoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/lookup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Purl != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "purl", *params.Purl, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.RepositoryUrl != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "repository_url", *params.RepositoryUrl, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdvisoriesPackagesRequest constructs an http.Request for the GetAdvisoriesPackages method
func NewGetAdvisoriesPackagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/packages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdvisoryRequest constructs an http.Request for the GetAdvisory method
func NewGetAdvisoryRequest(server string, advisoryUUID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "advisoryUUID", advisoryUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/advisories/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourcesRequest constructs an http.Request for the GetSources method
func NewGetSourcesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourceRequest constructs an http.Request for the GetSource method
func NewGetSourceRequest(server string, sourceKind string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sourceKind", sourceKind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetAdvisoriesWithResponse list advisories
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /advisories (the `GetAdvisories` operationId).
	GetAdvisoriesWithResponse(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*GetAdvisoriesResponse, error)

	// LookupAdvisoriesWithResponse lookup advisories by Package URL (PURL) or repository URL
	//
	// Lookup security advisories for a package using Package URL (PURL) specification or by source repository URL. One of purl or repository_url must be provided. Results are deduplicated by CVE identifier.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /advisories/lookup (the `LookupAdvisories` operationId).
	LookupAdvisoriesWithResponse(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*LookupAdvisoriesResponse, error)

	// GetAdvisoriesPackagesWithResponse list packages that have advisories
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /advisories/packages (the `GetAdvisoriesPackages` operationId).
	GetAdvisoriesPackagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdvisoriesPackagesResponse, error)

	// GetAdvisoryWithResponse get an advisory by uuid
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /advisories/{advisoryUUID} (the `GetAdvisory` operationId).
	GetAdvisoryWithResponse(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*GetAdvisoryResponse, error)

	// GetSourcesWithResponse list advisory sources
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sources (the `GetSources` operationId).
	GetSourcesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcesResponse, error)

	// GetSourceWithResponse get a source by kind
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sources/{sourceKind} (the `GetSource` operationId).
	GetSourceWithResponse(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)
}

type GetAdvisoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Advisory
}

// Status returns HTTPResponse.Status
func (r GetAdvisoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdvisoriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupAdvisoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Advisory
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *LookupAdvisories400JSONResponseBody
}

// Status returns HTTPResponse.Status
func (r LookupAdvisoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupAdvisoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupAdvisoriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdvisoriesPackagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Package
}

// Status returns HTTPResponse.Status
func (r GetAdvisoriesPackagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoriesPackagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdvisoriesPackagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdvisoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Advisory
}

// Status returns HTTPResponse.Status
func (r GetAdvisoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdvisoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdvisoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSourcesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Source
}

// Status returns HTTPResponse.Status
func (r GetSourcesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourcesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSourcesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Source
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAdvisoriesWithResponse list advisories
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /advisories (the `GetAdvisories` operationId).
func (c *ClientWithResponses) GetAdvisoriesWithResponse(ctx context.Context, params *GetAdvisoriesParams, reqEditors ...RequestEditorFn) (*GetAdvisoriesResponse, error) {
	rsp, err := c.GetAdvisories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoriesResponse(rsp)
}

// LookupAdvisoriesWithResponse lookup advisories by Package URL (PURL) or repository URL
//
// Lookup security advisories for a package using Package URL (PURL) specification or by source repository URL. One of purl or repository_url must be provided. Results are deduplicated by CVE identifier.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /advisories/lookup (the `LookupAdvisories` operationId).
func (c *ClientWithResponses) LookupAdvisoriesWithResponse(ctx context.Context, params *LookupAdvisoriesParams, reqEditors ...RequestEditorFn) (*LookupAdvisoriesResponse, error) {
	rsp, err := c.LookupAdvisories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupAdvisoriesResponse(rsp)
}

// GetAdvisoriesPackagesWithResponse list packages that have advisories
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /advisories/packages (the `GetAdvisoriesPackages` operationId).
func (c *ClientWithResponses) GetAdvisoriesPackagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdvisoriesPackagesResponse, error) {
	rsp, err := c.GetAdvisoriesPackages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoriesPackagesResponse(rsp)
}

// GetAdvisoryWithResponse get an advisory by uuid
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /advisories/{advisoryUUID} (the `GetAdvisory` operationId).
func (c *ClientWithResponses) GetAdvisoryWithResponse(ctx context.Context, advisoryUUID string, reqEditors ...RequestEditorFn) (*GetAdvisoryResponse, error) {
	rsp, err := c.GetAdvisory(ctx, advisoryUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdvisoryResponse(rsp)
}

// GetSourcesWithResponse list advisory sources
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sources (the `GetSources` operationId).
func (c *ClientWithResponses) GetSourcesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcesResponse, error) {
	rsp, err := c.GetSources(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourcesResponse(rsp)
}

// GetSourceWithResponse get a source by kind
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sources/{sourceKind} (the `GetSource` operationId).
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, sourceKind string, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, sourceKind, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// ParseGetAdvisoriesResponse parses an HTTP response from a GetAdvisoriesWithResponse call
func ParseGetAdvisoriesResponse(rsp *http.Response) (*GetAdvisoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLookupAdvisoriesResponse parses an HTTP response from a LookupAdvisoriesWithResponse call
func ParseLookupAdvisoriesResponse(rsp *http.Response) (*LookupAdvisoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupAdvisoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest LookupAdvisories400JSONResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetAdvisoriesPackagesResponse parses an HTTP response from a GetAdvisoriesPackagesWithResponse call
func ParseGetAdvisoriesPackagesResponse(rsp *http.Response) (*GetAdvisoriesPackagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoriesPackagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Package
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAdvisoryResponse parses an HTTP response from a GetAdvisoryWithResponse call
func ParseGetAdvisoryResponse(rsp *http.Response) (*GetAdvisoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdvisoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Advisory
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSourcesResponse parses an HTTP response from a GetSourcesWithResponse call
func ParseGetSourcesResponse(rsp *http.Response) (*GetSourcesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourcesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
