// Package issues provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package issues

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Author defines model for Author.
type Author struct {
	ActiveMaintaining                  []RepoCount              `json:"active_maintaining,omitempty"`
	AverageIssueCloseTime              *float32                 `json:"average_issue_close_time,omitempty"`
	AverageIssueCommentsCount          *float32                 `json:"average_issue_comments_count,omitempty"`
	AveragePullRequestCloseTime        *float32                 `json:"average_pull_request_close_time,omitempty"`
	AveragePullRequestCommentsCount    *float32                 `json:"average_pull_request_comments_count,omitempty"`
	IssueAuthorAssociationsCount       []AuthorAssociationCount `json:"issue_author_associations_count,omitempty"`
	IssueLabelsCount                   []LabelCount             `json:"issue_labels_count,omitempty"`
	IssueRepos                         []RepoCount              `json:"issue_repos,omitempty"`
	IssuesCount                        *int                     `json:"issues_count,omitempty"`
	Login                              *string                  `json:"login,omitempty"`
	Maintaining                        []RepoCount              `json:"maintaining,omitempty"`
	MergedPullRequestsCount            *int                     `json:"merged_pull_requests_count,omitempty"`
	PullRequestAuthorAssociationsCount []AuthorAssociationCount `json:"pull_request_author_associations_count,omitempty"`
	PullRequestLabelsCount             []LabelCount             `json:"pull_request_labels_count,omitempty"`
	PullRequestRepos                   []RepoCount              `json:"pull_request_repos,omitempty"`
	PullRequestsCount                  *int                     `json:"pull_requests_count,omitempty"`
}

// AuthorAssociationCount defines model for AuthorAssociationCount.
type AuthorAssociationCount struct {
	AuthorAssociation *string `json:"author_association,omitempty"`
	Count             *int    `json:"count,omitempty"`
}

// AuthorCount defines model for AuthorCount.
type AuthorCount struct {
	Author *string `json:"author,omitempty"`
	Count  *int    `json:"count,omitempty"`
	URL    *string `json:"url,omitempty"`
}

// AuthorSummary defines model for AuthorSummary.
type AuthorSummary struct {
	AuthorURL         *string `json:"author_url,omitempty"`
	Login             *string `json:"login,omitempty"`
	RepositoriesCount *int    `json:"repositories_count,omitempty"`
}

// Host defines model for Host.
type Host struct {
	AuthorsCount      *int       `json:"authors_count,omitempty"`
	IconURL           *string    `json:"icon_url,omitempty"`
	IssuesCount       *int       `json:"issues_count,omitempty"`
	Kind              *string    `json:"kind,omitempty"`
	LastSyncedAt      *time.Time `json:"last_synced_at,omitempty"`
	Name              *string    `json:"name,omitempty"`
	PullRequestsCount *int       `json:"pull_requests_count,omitempty"`
	RepositoriesCount *int       `json:"repositories_count,omitempty"`
	URL               *string    `json:"url,omitempty"`
}

// Issue defines model for Issue.
type Issue struct {
	Assignees         []string   `json:"assignees,omitempty"`
	AuthorAssociation *string    `json:"author_association,omitempty"`
	ClosedAt          *time.Time `json:"closed_at,omitempty"`
	Comments          *int       `json:"comments,omitempty"`
	CommentsCount     *int       `json:"comments_count,omitempty"`
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	HTMLURL           *string    `json:"html_url,omitempty"`
	Labels            []string   `json:"labels,omitempty"`
	Locked            *bool      `json:"locked,omitempty"`
	MergedAt          *time.Time `json:"merged_at,omitempty"`
	NodeID            *string    `json:"node_id,omitempty"`
	Number            *int       `json:"number,omitempty"`
	PullRequest       *bool      `json:"pull_request,omitempty"`
	State             *string    `json:"state,omitempty"`
	StateReason       *string    `json:"state_reason,omitempty"`
	TimeToClose       *int       `json:"time_to_close,omitempty"`
	Title             *string    `json:"title,omitempty"`
	UpdatedAt         *time.Time `json:"updated_at,omitempty"`
	URL               *string    `json:"url,omitempty"`
	User              *string    `json:"user,omitempty"`
	UUID              *int       `json:"uuid,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt *time.Time             `json:"created_at,omitempty"`
	ID        *int                   `json:"id,omitempty"`
	Results   map[string]interface{} `json:"results,omitempty"`
	SidekiqID *string                `json:"sidekiq_id,omitempty"`
	Status    *string                `json:"status,omitempty"`
	UpdatedAt *time.Time             `json:"updated_at,omitempty"`
	URL       *string                `json:"url,omitempty"`
}

// LabelCount defines model for LabelCount.
type LabelCount struct {
	Count     *int    `json:"count,omitempty"`
	IssuesURL *string `json:"issues_url,omitempty"`
	Label     *string `json:"label,omitempty"`
}

// MaintainerCount defines model for MaintainerCount.
type MaintainerCount struct {
	Count      *int    `json:"count,omitempty"`
	Maintainer *string `json:"maintainer,omitempty"`
	URL        *string `json:"url,omitempty"`
}

// Maintainers defines model for Maintainers.
type Maintainers struct {
	ActiveMaintainers []MaintainerCount `json:"active_maintainers,omitempty"`
	Login             *string           `json:"login,omitempty"`
	Maintainers       []MaintainerCount `json:"maintainers,omitempty"`
}

// Owner defines model for Owner.
type Owner struct {
	ActiveMaintainers                  []MaintainerCount        `json:"active_maintainers,omitempty"`
	AverageIssueCloseTime              *float32                 `json:"average_issue_close_time,omitempty"`
	AverageIssueCommentsCount          *float32                 `json:"average_issue_comments_count,omitempty"`
	AveragePullRequestCloseTime        *float32                 `json:"average_pull_request_close_time,omitempty"`
	AveragePullRequestCommentsCount    *float32                 `json:"average_pull_request_comments_count,omitempty"`
	IssueAuthorAssociationsCount       []AuthorAssociationCount `json:"issue_author_associations_count,omitempty"`
	IssueAuthors                       []AuthorCount            `json:"issue_authors,omitempty"`
	IssueLabelsCount                   []LabelCount             `json:"issue_labels_count,omitempty"`
	IssueRepos                         []RepoCount              `json:"issue_repos,omitempty"`
	IssuesCount                        *int                     `json:"issues_count,omitempty"`
	Login                              *string                  `json:"login,omitempty"`
	Maintainers                        []MaintainerCount        `json:"maintainers,omitempty"`
	MergedPullRequestsCount            *int                     `json:"merged_pull_requests_count,omitempty"`
	PullRequestAuthorAssociationsCount []AuthorAssociationCount `json:"pull_request_author_associations_count,omitempty"`
	PullRequestAuthors                 []AuthorCount            `json:"pull_request_authors,omitempty"`
	PullRequestLabelsCount             []LabelCount             `json:"pull_request_labels_count,omitempty"`
	PullRequestRepos                   []RepoCount              `json:"pull_request_repos,omitempty"`
	PullRequestsCount                  *int                     `json:"pull_requests_count,omitempty"`
}

// OwnerSummary defines model for OwnerSummary.
type OwnerSummary struct {
	Login             *string `json:"login,omitempty"`
	OwnerURL          *string `json:"owner_url,omitempty"`
	RepositoriesCount *int    `json:"repositories_count,omitempty"`
}

// RepoCount defines model for RepoCount.
type RepoCount struct {
	Count      *int    `json:"count,omitempty"`
	Repository *string `json:"repository,omitempty"`
	URL        *string `json:"url,omitempty"`
}

// Repository defines model for Repository.
type Repository struct {
	AvgCommentsPerIssue               *float32   `json:"avg_comments_per_issue,omitempty"`
	AvgCommentsPerPullRequest         *float32   `json:"avg_comments_per_pull_request,omitempty"`
	AvgTimeToCloseIssue               *float32   `json:"avg_time_to_close_issue,omitempty"`
	AvgTimeToClosePullRequest         *float32   `json:"avg_time_to_close_pull_request,omitempty"`
	BotIssuesCount                    *int       `json:"bot_issues_count,omitempty"`
	BotPullRequestsCount              *int       `json:"bot_pull_requests_count,omitempty"`
	CreatedAt                         *time.Time `json:"created_at,omitempty"`
	FullName                          *string    `json:"full_name,omitempty"`
	HTMLURL                           *string    `json:"html_url,omitempty"`
	IssueAuthorsCount                 *int       `json:"issue_authors_count,omitempty"`
	IssuesClosedCount                 *int       `json:"issues_closed_count,omitempty"`
	IssuesCount                       *int       `json:"issues_count,omitempty"`
	IssuesURL                         *string    `json:"issues_url,omitempty"`
	LastSyncedAt                      *time.Time `json:"last_synced_at,omitempty"`
	MergedPullRequestsCount           *int       `json:"merged_pull_requests_count,omitempty"`
	PastYearAvgCommentsPerIssue       *float32   `json:"past_year_avg_comments_per_issue,omitempty"`
	PastYearAvgCommentsPerPullRequest *float32   `json:"past_year_avg_comments_per_pull_request,omitempty"`
	PastYearAvgTimeToCloseIssue       *float32   `json:"past_year_avg_time_to_close_issue,omitempty"`
	PastYearAvgTimeToClosePullRequest *float32   `json:"past_year_avg_time_to_close_pull_request,omitempty"`
	PastYearBotIssuesCount            *int       `json:"past_year_bot_issues_count,omitempty"`
	PastYearBotPullRequestsCount      *int       `json:"past_year_bot_pull_requests_count,omitempty"`
	PastYearIssueAuthorsCount         *int       `json:"past_year_issue_authors_count,omitempty"`
	PastYearIssuesClosedCount         *int       `json:"past_year_issues_closed_count,omitempty"`
	PastYearIssuesCount               *int       `json:"past_year_issues_count,omitempty"`
	PastYearMergedPullRequestsCount   *int       `json:"past_year_merged_pull_requests_count,omitempty"`
	PastYearPullRequestAuthorsCount   *int       `json:"past_year_pull_request_authors_count,omitempty"`
	PastYearPullRequestsClosedCount   *int       `json:"past_year_pull_requests_closed_count,omitempty"`
	PastYearPullRequestsCount         *int       `json:"past_year_pull_requests_count,omitempty"`
	PullRequestAuthorsCount           *int       `json:"pull_request_authors_count,omitempty"`
	PullRequestsClosedCount           *int       `json:"pull_requests_closed_count,omitempty"`
	PullRequestsCount                 *int       `json:"pull_requests_count,omitempty"`
	Status                            *string    `json:"status,omitempty"`
	UpdatedAt                         *time.Time `json:"updated_at,omitempty"`
}

// GetRegistriesParams defines parameters for GetRegistries.
type GetRegistriesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostAuthorsParams defines parameters for GetHostAuthors.
type GetHostAuthorsParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostOwnersParams defines parameters for GetHostOwners.
type GetHostOwnersParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostRepositoriesParams defines parameters for GetHostRepositories.
type GetHostRepositoriesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// GetHostRepositoryIssuesParams defines parameters for GetHostRepositoryIssues.
type GetHostRepositoryIssuesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`

	// PullRequest filter by if it's a pull request
	PullRequest *bool `form:"pull_request,omitempty" json:"pull_request,omitempty"`

	// State filter by issue state (open, closed)
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Label filter by label name
	Label *string `form:"label,omitempty" json:"label,omitempty"`
}

// CreateJobJSONBody defines parameters for CreateJob.
type CreateJobJSONBody struct {
	// URL URL of the repository to sync issues from
	URL string `json:"url"`
}

// CreateJob400JSONResponseBody defines parameters for CreateJob.
type CreateJob400JSONResponseBody struct {
	Details []string `json:"details,omitempty"`
	Title   *string  `json:"title,omitempty"`
}

// RepositoriesLookupParams defines parameters for RepositoriesLookup.
type RepositoriesLookupParams struct {
	// URL The URL of the repository to lookup
	URL string `form:"url" json:"url"`
}

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody CreateJobJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetRegistries list registries
	//
	// Corresponds with GET /hosts (the `GetRegistries` operationId).
	GetRegistries(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHost get a host by name
	//
	// Corresponds with GET /hosts/{hostName} (the `GetHost` operationId).
	GetHost(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostAuthors get a list of authors from a host
	//
	// Corresponds with GET /hosts/{hostName}/authors (the `GetHostAuthors` operationId).
	GetHostAuthors(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostAuthor get author statistics from a host
	//
	// Corresponds with GET /hosts/{hostName}/authors/{authorName} (the `GetHostAuthor` operationId).
	GetHostAuthor(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwners get a list of owners from a host
	//
	// Corresponds with GET /hosts/{hostName}/owners (the `GetHostOwners` operationId).
	GetHostOwners(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwner get owner statistics from a host
	//
	// Corresponds with GET /hosts/{hostName}/owners/{ownerName} (the `GetHostOwner` operationId).
	GetHostOwner(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwnerMaintainers get maintainers for an owner
	//
	// Corresponds with GET /hosts/{hostName}/owners/{ownerName}/maintainers (the `GetHostOwnerMaintainers` operationId).
	GetHostOwnerMaintainers(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositories get a list of repositories from a host
	//
	// Corresponds with GET /hosts/{hostName}/repositories (the `GetHostRepositories` operationId).
	GetHostRepositories(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepository get a repository from a host
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName} (the `GetHostRepository` operationId).
	GetHostRepository(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryIssues get a list of issues from a repository
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues (the `GetHostRepositoryIssues` operationId).
	GetHostRepositoryIssues(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryIssue get an issue from a repository
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues/{issueNumber} (the `GetHostRepositoryIssue` operationId).
	GetHostRepositoryIssue(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryLabels get a list of labels used in issues for a repository
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/labels (the `GetHostRepositoryLabels` operationId).
	GetHostRepositoryLabels(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJobWithBody create a job to sync issues from a URL
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /jobs (the `CreateJob` operationId).
	CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJob create a job to sync issues from a URL
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /jobs (the `CreateJob` operationId).
	CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob get the status of a job
	//
	// Corresponds with GET /jobs/{jobId} (the `GetJob` operationId).
	GetJob(ctx context.Context, jobID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RepositoriesLookup Lookup repository metadata
	//
	// Corresponds with GET /repositories/lookup (the `RepositoriesLookup` operationId).
	RepositoriesLookup(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetRegistries list registries
//
// Corresponds with GET /hosts (the `GetRegistries` operationId).
func (c *Client) GetRegistries(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRegistriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHost get a host by name
//
// Corresponds with GET /hosts/{hostName} (the `GetHost` operationId).
func (c *Client) GetHost(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRequest(c.Server, hostName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostAuthors get a list of authors from a host
//
// Corresponds with GET /hosts/{hostName}/authors (the `GetHostAuthors` operationId).
func (c *Client) GetHostAuthors(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostAuthorsRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostAuthor get author statistics from a host
//
// Corresponds with GET /hosts/{hostName}/authors/{authorName} (the `GetHostAuthor` operationId).
func (c *Client) GetHostAuthor(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostAuthorRequest(c.Server, hostName, authorName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostOwners get a list of owners from a host
//
// Corresponds with GET /hosts/{hostName}/owners (the `GetHostOwners` operationId).
func (c *Client) GetHostOwners(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnersRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostOwner get owner statistics from a host
//
// Corresponds with GET /hosts/{hostName}/owners/{ownerName} (the `GetHostOwner` operationId).
func (c *Client) GetHostOwner(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnerRequest(c.Server, hostName, ownerName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostOwnerMaintainers get maintainers for an owner
//
// Corresponds with GET /hosts/{hostName}/owners/{ownerName}/maintainers (the `GetHostOwnerMaintainers` operationId).
func (c *Client) GetHostOwnerMaintainers(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnerMaintainersRequest(c.Server, hostName, ownerName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostRepositories get a list of repositories from a host
//
// Corresponds with GET /hosts/{hostName}/repositories (the `GetHostRepositories` operationId).
func (c *Client) GetHostRepositories(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoriesRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostRepository get a repository from a host
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName} (the `GetHostRepository` operationId).
func (c *Client) GetHostRepository(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryRequest(c.Server, hostName, repoName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostRepositoryIssues get a list of issues from a repository
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues (the `GetHostRepositoryIssues` operationId).
func (c *Client) GetHostRepositoryIssues(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryIssuesRequest(c.Server, hostName, repoName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostRepositoryIssue get an issue from a repository
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues/{issueNumber} (the `GetHostRepositoryIssue` operationId).
func (c *Client) GetHostRepositoryIssue(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryIssueRequest(c.Server, hostName, repoName, issueNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHostRepositoryLabels get a list of labels used in issues for a repository
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/labels (the `GetHostRepositoryLabels` operationId).
func (c *Client) GetHostRepositoryLabels(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryLabelsRequest(c.Server, hostName, repoName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateJobWithBody create a job to sync issues from a URL
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /jobs (the `CreateJob` operationId).
func (c *Client) CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateJob create a job to sync issues from a URL
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /jobs (the `CreateJob` operationId).
func (c *Client) CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetJob get the status of a job
//
// Corresponds with GET /jobs/{jobId} (the `GetJob` operationId).
func (c *Client) GetJob(ctx context.Context, jobID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RepositoriesLookup Lookup repository metadata
//
// Corresponds with GET /repositories/lookup (the `RepositoriesLookup` operationId).
func (c *Client) RepositoriesLookup(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRepositoriesLookupRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRegistriesRequest constructs an http.Request for the GetRegistries method
func NewGetRegistriesRequest(server string, params *GetRegistriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRequest constructs an http.Request for the GetHost method
func NewGetHostRequest(server string, hostName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostAuthorsRequest constructs an http.Request for the GetHostAuthors method
func NewGetHostAuthorsRequest(server string, hostName string, params *GetHostAuthorsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/authors", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostAuthorRequest constructs an http.Request for the GetHostAuthor method
func NewGetHostAuthorRequest(server string, hostName string, authorName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "authorName", authorName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/authors/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnersRequest constructs an http.Request for the GetHostOwners method
func NewGetHostOwnersRequest(server string, hostName string, params *GetHostOwnersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnerRequest constructs an http.Request for the GetHostOwner method
func NewGetHostOwnerRequest(server string, hostName string, ownerName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ownerName", ownerName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnerMaintainersRequest constructs an http.Request for the GetHostOwnerMaintainers method
func NewGetHostOwnerMaintainersRequest(server string, hostName string, ownerName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ownerName", ownerName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners/%s/maintainers", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoriesRequest constructs an http.Request for the GetHostRepositories method
func NewGetHostRepositoriesRequest(server string, hostName string, params *GetHostRepositoriesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_after", *params.CreatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "updated_after", *params.UpdatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "order", *params.Order, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryRequest constructs an http.Request for the GetHostRepository method
func NewGetHostRepositoryRequest(server string, hostName string, repoName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repoName", repoName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryIssuesRequest constructs an http.Request for the GetHostRepositoryIssues method
func NewGetHostRepositoryIssuesRequest(server string, hostName string, repoName string, params *GetHostRepositoryIssuesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repoName", repoName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/issues", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_after", *params.CreatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "updated_after", *params.UpdatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "order", *params.Order, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PullRequest != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pull_request", *params.PullRequest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Label != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "label", *params.Label, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryIssueRequest constructs an http.Request for the GetHostRepositoryIssue method
func NewGetHostRepositoryIssueRequest(server string, hostName string, repoName string, issueNumber int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repoName", repoName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "issueNumber", issueNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/issues/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryLabelsRequest constructs an http.Request for the GetHostRepositoryLabels method
func NewGetHostRepositoryLabelsRequest(server string, hostName string, repoName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "hostName", hostName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repoName", repoName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/labels", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateJobRequest calls the generic CreateJob builder with application/json body
func NewCreateJobRequest(server string, body CreateJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateJobRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateJobRequestWithBody constructs an http.Request for the CreateJob method, with any body, and a specified content type
func NewCreateJobRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetJobRequest constructs an http.Request for the GetJob method
func NewGetJobRequest(server string, jobID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "jobId", jobID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRepositoriesLookupRequest constructs an http.Request for the RepositoriesLookup method
func NewRepositoriesLookupRequest(server string, params *RepositoriesLookupParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repositories/lookup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "url", params.URL, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetRegistriesWithResponse list registries
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts (the `GetRegistries` operationId).
	GetRegistriesWithResponse(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*GetRegistriesResponse, error)

	// GetHostWithResponse get a host by name
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName} (the `GetHost` operationId).
	GetHostWithResponse(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*GetHostResponse, error)

	// GetHostAuthorsWithResponse get a list of authors from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/authors (the `GetHostAuthors` operationId).
	GetHostAuthorsWithResponse(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*GetHostAuthorsResponse, error)

	// GetHostAuthorWithResponse get author statistics from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/authors/{authorName} (the `GetHostAuthor` operationId).
	GetHostAuthorWithResponse(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*GetHostAuthorResponse, error)

	// GetHostOwnersWithResponse get a list of owners from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/owners (the `GetHostOwners` operationId).
	GetHostOwnersWithResponse(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*GetHostOwnersResponse, error)

	// GetHostOwnerWithResponse get owner statistics from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/owners/{ownerName} (the `GetHostOwner` operationId).
	GetHostOwnerWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerResponse, error)

	// GetHostOwnerMaintainersWithResponse get maintainers for an owner
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/owners/{ownerName}/maintainers (the `GetHostOwnerMaintainers` operationId).
	GetHostOwnerMaintainersWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerMaintainersResponse, error)

	// GetHostRepositoriesWithResponse get a list of repositories from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/repositories (the `GetHostRepositories` operationId).
	GetHostRepositoriesWithResponse(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoriesResponse, error)

	// GetHostRepositoryWithResponse get a repository from a host
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName} (the `GetHostRepository` operationId).
	GetHostRepositoryWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryResponse, error)

	// GetHostRepositoryIssuesWithResponse get a list of issues from a repository
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues (the `GetHostRepositoryIssues` operationId).
	GetHostRepositoryIssuesWithResponse(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssuesResponse, error)

	// GetHostRepositoryIssueWithResponse get an issue from a repository
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues/{issueNumber} (the `GetHostRepositoryIssue` operationId).
	GetHostRepositoryIssueWithResponse(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssueResponse, error)

	// GetHostRepositoryLabelsWithResponse get a list of labels used in issues for a repository
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/labels (the `GetHostRepositoryLabels` operationId).
	GetHostRepositoryLabelsWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryLabelsResponse, error)

	// CreateJobWithBodyWithResponse create a job to sync issues from a URL
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /jobs (the `CreateJob` operationId).
	CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	// CreateJobWithResponse create a job to sync issues from a URL
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /jobs (the `CreateJob` operationId).
	CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	// GetJobWithResponse get the status of a job
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /jobs/{jobId} (the `GetJob` operationId).
	GetJobWithResponse(ctx context.Context, jobID int, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// RepositoriesLookupWithResponse Lookup repository metadata
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /repositories/lookup (the `RepositoriesLookup` operationId).
	RepositoriesLookupWithResponse(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*RepositoriesLookupResponse, error)
}

type GetRegistriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Host
}

// Status returns HTTPResponse.Status
func (r GetRegistriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRegistriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRegistriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Host
}

// Status returns HTTPResponse.Status
func (r GetHostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostAuthorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AuthorSummary
}

// Status returns HTTPResponse.Status
func (r GetHostAuthorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostAuthorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostAuthorsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostAuthorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Author
}

// Status returns HTTPResponse.Status
func (r GetHostAuthorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostAuthorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostAuthorResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostOwnersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]OwnerSummary
}

// Status returns HTTPResponse.Status
func (r GetHostOwnersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostOwnersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostOwnerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Owner
}

// Status returns HTTPResponse.Status
func (r GetHostOwnerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostOwnerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostOwnerMaintainersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Maintainers
}

// Status returns HTTPResponse.Status
func (r GetHostOwnerMaintainersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnerMaintainersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostOwnerMaintainersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostRepositoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Repository
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostRepositoriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostRepositoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Repository
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostRepositoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostRepositoryIssuesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Issue
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryIssuesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryIssuesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostRepositoryIssuesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostRepositoryIssueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Issue
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryIssueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryIssueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostRepositoryIssueResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHostRepositoryLabelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]LabelCount
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryLabelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryLabelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHostRepositoryLabelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *CreateJob400JSONResponseBody
}

// Status returns HTTPResponse.Status
func (r CreateJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Job
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RepositoriesLookupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Repository
}

// Status returns HTTPResponse.Status
func (r RepositoriesLookupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RepositoriesLookupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RepositoriesLookupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetRegistriesWithResponse list registries
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts (the `GetRegistries` operationId).
func (c *ClientWithResponses) GetRegistriesWithResponse(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*GetRegistriesResponse, error) {
	rsp, err := c.GetRegistries(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRegistriesResponse(rsp)
}

// GetHostWithResponse get a host by name
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName} (the `GetHost` operationId).
func (c *ClientWithResponses) GetHostWithResponse(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*GetHostResponse, error) {
	rsp, err := c.GetHost(ctx, hostName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostResponse(rsp)
}

// GetHostAuthorsWithResponse get a list of authors from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/authors (the `GetHostAuthors` operationId).
func (c *ClientWithResponses) GetHostAuthorsWithResponse(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*GetHostAuthorsResponse, error) {
	rsp, err := c.GetHostAuthors(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostAuthorsResponse(rsp)
}

// GetHostAuthorWithResponse get author statistics from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/authors/{authorName} (the `GetHostAuthor` operationId).
func (c *ClientWithResponses) GetHostAuthorWithResponse(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*GetHostAuthorResponse, error) {
	rsp, err := c.GetHostAuthor(ctx, hostName, authorName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostAuthorResponse(rsp)
}

// GetHostOwnersWithResponse get a list of owners from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/owners (the `GetHostOwners` operationId).
func (c *ClientWithResponses) GetHostOwnersWithResponse(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*GetHostOwnersResponse, error) {
	rsp, err := c.GetHostOwners(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnersResponse(rsp)
}

// GetHostOwnerWithResponse get owner statistics from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/owners/{ownerName} (the `GetHostOwner` operationId).
func (c *ClientWithResponses) GetHostOwnerWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerResponse, error) {
	rsp, err := c.GetHostOwner(ctx, hostName, ownerName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnerResponse(rsp)
}

// GetHostOwnerMaintainersWithResponse get maintainers for an owner
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/owners/{ownerName}/maintainers (the `GetHostOwnerMaintainers` operationId).
func (c *ClientWithResponses) GetHostOwnerMaintainersWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerMaintainersResponse, error) {
	rsp, err := c.GetHostOwnerMaintainers(ctx, hostName, ownerName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnerMaintainersResponse(rsp)
}

// GetHostRepositoriesWithResponse get a list of repositories from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/repositories (the `GetHostRepositories` operationId).
func (c *ClientWithResponses) GetHostRepositoriesWithResponse(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoriesResponse, error) {
	rsp, err := c.GetHostRepositories(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoriesResponse(rsp)
}

// GetHostRepositoryWithResponse get a repository from a host
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName} (the `GetHostRepository` operationId).
func (c *ClientWithResponses) GetHostRepositoryWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryResponse, error) {
	rsp, err := c.GetHostRepository(ctx, hostName, repoName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryResponse(rsp)
}

// GetHostRepositoryIssuesWithResponse get a list of issues from a repository
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues (the `GetHostRepositoryIssues` operationId).
func (c *ClientWithResponses) GetHostRepositoryIssuesWithResponse(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssuesResponse, error) {
	rsp, err := c.GetHostRepositoryIssues(ctx, hostName, repoName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryIssuesResponse(rsp)
}

// GetHostRepositoryIssueWithResponse get an issue from a repository
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/issues/{issueNumber} (the `GetHostRepositoryIssue` operationId).
func (c *ClientWithResponses) GetHostRepositoryIssueWithResponse(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssueResponse, error) {
	rsp, err := c.GetHostRepositoryIssue(ctx, hostName, repoName, issueNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryIssueResponse(rsp)
}

// GetHostRepositoryLabelsWithResponse get a list of labels used in issues for a repository
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /hosts/{hostName}/repositories/{repoName}/labels (the `GetHostRepositoryLabels` operationId).
func (c *ClientWithResponses) GetHostRepositoryLabelsWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryLabelsResponse, error) {
	rsp, err := c.GetHostRepositoryLabels(ctx, hostName, repoName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryLabelsResponse(rsp)
}

// CreateJobWithBodyWithResponse create a job to sync issues from a URL
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /jobs (the `CreateJob` operationId).
func (c *ClientWithResponses) CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJobWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

// CreateJobWithResponse create a job to sync issues from a URL
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /jobs (the `CreateJob` operationId).
func (c *ClientWithResponses) CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJob(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

// GetJobWithResponse get the status of a job
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /jobs/{jobId} (the `GetJob` operationId).
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobID int, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, jobID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// RepositoriesLookupWithResponse Lookup repository metadata
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /repositories/lookup (the `RepositoriesLookup` operationId).
func (c *ClientWithResponses) RepositoriesLookupWithResponse(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*RepositoriesLookupResponse, error) {
	rsp, err := c.RepositoriesLookup(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRepositoriesLookupResponse(rsp)
}

// ParseGetRegistriesResponse parses an HTTP response from a GetRegistriesWithResponse call
func ParseGetRegistriesResponse(rsp *http.Response) (*GetRegistriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRegistriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Host
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostResponse parses an HTTP response from a GetHostWithResponse call
func ParseGetHostResponse(rsp *http.Response) (*GetHostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Host
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostAuthorsResponse parses an HTTP response from a GetHostAuthorsWithResponse call
func ParseGetHostAuthorsResponse(rsp *http.Response) (*GetHostAuthorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostAuthorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AuthorSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostAuthorResponse parses an HTTP response from a GetHostAuthorWithResponse call
func ParseGetHostAuthorResponse(rsp *http.Response) (*GetHostAuthorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostAuthorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Author
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnersResponse parses an HTTP response from a GetHostOwnersWithResponse call
func ParseGetHostOwnersResponse(rsp *http.Response) (*GetHostOwnersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []OwnerSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnerResponse parses an HTTP response from a GetHostOwnerWithResponse call
func ParseGetHostOwnerResponse(rsp *http.Response) (*GetHostOwnerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Owner
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnerMaintainersResponse parses an HTTP response from a GetHostOwnerMaintainersWithResponse call
func ParseGetHostOwnerMaintainersResponse(rsp *http.Response) (*GetHostOwnerMaintainersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnerMaintainersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Maintainers
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoriesResponse parses an HTTP response from a GetHostRepositoriesWithResponse call
func ParseGetHostRepositoriesResponse(rsp *http.Response) (*GetHostRepositoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryResponse parses an HTTP response from a GetHostRepositoryWithResponse call
func ParseGetHostRepositoryResponse(rsp *http.Response) (*GetHostRepositoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryIssuesResponse parses an HTTP response from a GetHostRepositoryIssuesWithResponse call
func ParseGetHostRepositoryIssuesResponse(rsp *http.Response) (*GetHostRepositoryIssuesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryIssuesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Issue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryIssueResponse parses an HTTP response from a GetHostRepositoryIssueWithResponse call
func ParseGetHostRepositoryIssueResponse(rsp *http.Response) (*GetHostRepositoryIssueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryIssueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Issue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryLabelsResponse parses an HTTP response from a GetHostRepositoryLabelsWithResponse call
func ParseGetHostRepositoryLabelsResponse(rsp *http.Response) (*GetHostRepositoryLabelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryLabelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []LabelCount
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateJobResponse parses an HTTP response from a CreateJobWithResponse call
func ParseCreateJobResponse(rsp *http.Response) (*CreateJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 302:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CreateJob400JSONResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRepositoriesLookupResponse parses an HTTP response from a RepositoriesLookupWithResponse call
func ParseRepositoriesLookupResponse(rsp *http.Response) (*RepositoriesLookupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RepositoriesLookupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
