// Package issues provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package issues

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Author defines model for Author.
type Author struct {
	ActiveMaintaining                  *[]RepoCount              `json:"active_maintaining,omitempty"`
	AverageIssueCloseTime              *float32                  `json:"average_issue_close_time,omitempty"`
	AverageIssueCommentsCount          *float32                  `json:"average_issue_comments_count,omitempty"`
	AveragePullRequestCloseTime        *float32                  `json:"average_pull_request_close_time,omitempty"`
	AveragePullRequestCommentsCount    *float32                  `json:"average_pull_request_comments_count,omitempty"`
	IssueAuthorAssociationsCount       *[]AuthorAssociationCount `json:"issue_author_associations_count,omitempty"`
	IssueLabelsCount                   *[]LabelCount             `json:"issue_labels_count,omitempty"`
	IssueRepos                         *[]RepoCount              `json:"issue_repos,omitempty"`
	IssuesCount                        *int                      `json:"issues_count,omitempty"`
	Login                              *string                   `json:"login,omitempty"`
	Maintaining                        *[]RepoCount              `json:"maintaining,omitempty"`
	MergedPullRequestsCount            *int                      `json:"merged_pull_requests_count,omitempty"`
	PullRequestAuthorAssociationsCount *[]AuthorAssociationCount `json:"pull_request_author_associations_count,omitempty"`
	PullRequestLabelsCount             *[]LabelCount             `json:"pull_request_labels_count,omitempty"`
	PullRequestRepos                   *[]RepoCount              `json:"pull_request_repos,omitempty"`
	PullRequestsCount                  *int                      `json:"pull_requests_count,omitempty"`
}

// AuthorAssociationCount defines model for AuthorAssociationCount.
type AuthorAssociationCount struct {
	AuthorAssociation *string `json:"author_association,omitempty"`
	Count             *int    `json:"count,omitempty"`
}

// AuthorCount defines model for AuthorCount.
type AuthorCount struct {
	Author *string `json:"author,omitempty"`
	Count  *int    `json:"count,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// AuthorSummary defines model for AuthorSummary.
type AuthorSummary struct {
	AuthorUrl         *string `json:"author_url,omitempty"`
	Login             *string `json:"login,omitempty"`
	RepositoriesCount *int    `json:"repositories_count,omitempty"`
}

// Host defines model for Host.
type Host struct {
	AuthorsCount      *int       `json:"authors_count,omitempty"`
	IconUrl           *string    `json:"icon_url,omitempty"`
	IssuesCount       *int       `json:"issues_count,omitempty"`
	Kind              *string    `json:"kind,omitempty"`
	LastSyncedAt      *time.Time `json:"last_synced_at,omitempty"`
	Name              *string    `json:"name,omitempty"`
	PullRequestsCount *int       `json:"pull_requests_count,omitempty"`
	RepositoriesCount *int       `json:"repositories_count,omitempty"`
	Url               *string    `json:"url,omitempty"`
}

// Issue defines model for Issue.
type Issue struct {
	Assignees         *[]string  `json:"assignees,omitempty"`
	AuthorAssociation *string    `json:"author_association,omitempty"`
	ClosedAt          *time.Time `json:"closed_at,omitempty"`
	Comments          *int       `json:"comments,omitempty"`
	CommentsCount     *int       `json:"comments_count,omitempty"`
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	HtmlUrl           *string    `json:"html_url,omitempty"`
	Labels            *[]string  `json:"labels,omitempty"`
	Locked            *bool      `json:"locked,omitempty"`
	MergedAt          *time.Time `json:"merged_at,omitempty"`
	NodeId            *string    `json:"node_id,omitempty"`
	Number            *int       `json:"number,omitempty"`
	PullRequest       *bool      `json:"pull_request,omitempty"`
	State             *string    `json:"state,omitempty"`
	StateReason       *string    `json:"state_reason,omitempty"`
	TimeToClose       *int       `json:"time_to_close,omitempty"`
	Title             *string    `json:"title,omitempty"`
	UpdatedAt         *time.Time `json:"updated_at,omitempty"`
	Url               *string    `json:"url,omitempty"`
	User              *string    `json:"user,omitempty"`
	Uuid              *int       `json:"uuid,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt *time.Time              `json:"created_at,omitempty"`
	Id        *int                    `json:"id,omitempty"`
	Results   *map[string]interface{} `json:"results,omitempty"`
	SidekiqId *string                 `json:"sidekiq_id,omitempty"`
	Status    *string                 `json:"status,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`
	Url       *string                 `json:"url,omitempty"`
}

// LabelCount defines model for LabelCount.
type LabelCount struct {
	Count     *int    `json:"count,omitempty"`
	IssuesUrl *string `json:"issues_url,omitempty"`
	Label     *string `json:"label,omitempty"`
}

// MaintainerCount defines model for MaintainerCount.
type MaintainerCount struct {
	Count      *int    `json:"count,omitempty"`
	Maintainer *string `json:"maintainer,omitempty"`
	Url        *string `json:"url,omitempty"`
}

// Maintainers defines model for Maintainers.
type Maintainers struct {
	ActiveMaintainers *[]MaintainerCount `json:"active_maintainers,omitempty"`
	Login             *string            `json:"login,omitempty"`
	Maintainers       *[]MaintainerCount `json:"maintainers,omitempty"`
}

// Owner defines model for Owner.
type Owner struct {
	ActiveMaintainers                  *[]MaintainerCount        `json:"active_maintainers,omitempty"`
	AverageIssueCloseTime              *float32                  `json:"average_issue_close_time,omitempty"`
	AverageIssueCommentsCount          *float32                  `json:"average_issue_comments_count,omitempty"`
	AveragePullRequestCloseTime        *float32                  `json:"average_pull_request_close_time,omitempty"`
	AveragePullRequestCommentsCount    *float32                  `json:"average_pull_request_comments_count,omitempty"`
	IssueAuthorAssociationsCount       *[]AuthorAssociationCount `json:"issue_author_associations_count,omitempty"`
	IssueAuthors                       *[]AuthorCount            `json:"issue_authors,omitempty"`
	IssueLabelsCount                   *[]LabelCount             `json:"issue_labels_count,omitempty"`
	IssueRepos                         *[]RepoCount              `json:"issue_repos,omitempty"`
	IssuesCount                        *int                      `json:"issues_count,omitempty"`
	Login                              *string                   `json:"login,omitempty"`
	Maintainers                        *[]MaintainerCount        `json:"maintainers,omitempty"`
	MergedPullRequestsCount            *int                      `json:"merged_pull_requests_count,omitempty"`
	PullRequestAuthorAssociationsCount *[]AuthorAssociationCount `json:"pull_request_author_associations_count,omitempty"`
	PullRequestAuthors                 *[]AuthorCount            `json:"pull_request_authors,omitempty"`
	PullRequestLabelsCount             *[]LabelCount             `json:"pull_request_labels_count,omitempty"`
	PullRequestRepos                   *[]RepoCount              `json:"pull_request_repos,omitempty"`
	PullRequestsCount                  *int                      `json:"pull_requests_count,omitempty"`
}

// OwnerSummary defines model for OwnerSummary.
type OwnerSummary struct {
	Login             *string `json:"login,omitempty"`
	OwnerUrl          *string `json:"owner_url,omitempty"`
	RepositoriesCount *int    `json:"repositories_count,omitempty"`
}

// RepoCount defines model for RepoCount.
type RepoCount struct {
	Count      *int    `json:"count,omitempty"`
	Repository *string `json:"repository,omitempty"`
	Url        *string `json:"url,omitempty"`
}

// Repository defines model for Repository.
type Repository struct {
	AvgCommentsPerIssue               *float32   `json:"avg_comments_per_issue,omitempty"`
	AvgCommentsPerPullRequest         *float32   `json:"avg_comments_per_pull_request,omitempty"`
	AvgTimeToCloseIssue               *float32   `json:"avg_time_to_close_issue,omitempty"`
	AvgTimeToClosePullRequest         *float32   `json:"avg_time_to_close_pull_request,omitempty"`
	BotIssuesCount                    *int       `json:"bot_issues_count,omitempty"`
	BotPullRequestsCount              *int       `json:"bot_pull_requests_count,omitempty"`
	CreatedAt                         *time.Time `json:"created_at,omitempty"`
	FullName                          *string    `json:"full_name,omitempty"`
	HtmlUrl                           *string    `json:"html_url,omitempty"`
	IssueAuthorsCount                 *int       `json:"issue_authors_count,omitempty"`
	IssuesClosedCount                 *int       `json:"issues_closed_count,omitempty"`
	IssuesCount                       *int       `json:"issues_count,omitempty"`
	IssuesUrl                         *string    `json:"issues_url,omitempty"`
	LastSyncedAt                      *time.Time `json:"last_synced_at,omitempty"`
	MergedPullRequestsCount           *int       `json:"merged_pull_requests_count,omitempty"`
	PastYearAvgCommentsPerIssue       *float32   `json:"past_year_avg_comments_per_issue,omitempty"`
	PastYearAvgCommentsPerPullRequest *float32   `json:"past_year_avg_comments_per_pull_request,omitempty"`
	PastYearAvgTimeToCloseIssue       *float32   `json:"past_year_avg_time_to_close_issue,omitempty"`
	PastYearAvgTimeToClosePullRequest *float32   `json:"past_year_avg_time_to_close_pull_request,omitempty"`
	PastYearBotIssuesCount            *int       `json:"past_year_bot_issues_count,omitempty"`
	PastYearBotPullRequestsCount      *int       `json:"past_year_bot_pull_requests_count,omitempty"`
	PastYearIssueAuthorsCount         *int       `json:"past_year_issue_authors_count,omitempty"`
	PastYearIssuesClosedCount         *int       `json:"past_year_issues_closed_count,omitempty"`
	PastYearIssuesCount               *int       `json:"past_year_issues_count,omitempty"`
	PastYearMergedPullRequestsCount   *int       `json:"past_year_merged_pull_requests_count,omitempty"`
	PastYearPullRequestAuthorsCount   *int       `json:"past_year_pull_request_authors_count,omitempty"`
	PastYearPullRequestsClosedCount   *int       `json:"past_year_pull_requests_closed_count,omitempty"`
	PastYearPullRequestsCount         *int       `json:"past_year_pull_requests_count,omitempty"`
	PullRequestAuthorsCount           *int       `json:"pull_request_authors_count,omitempty"`
	PullRequestsClosedCount           *int       `json:"pull_requests_closed_count,omitempty"`
	PullRequestsCount                 *int       `json:"pull_requests_count,omitempty"`
	Status                            *string    `json:"status,omitempty"`
	UpdatedAt                         *time.Time `json:"updated_at,omitempty"`
}

// GetRegistriesParams defines parameters for GetRegistries.
type GetRegistriesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostAuthorsParams defines parameters for GetHostAuthors.
type GetHostAuthorsParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostOwnersParams defines parameters for GetHostOwners.
type GetHostOwnersParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetHostRepositoriesParams defines parameters for GetHostRepositories.
type GetHostRepositoriesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// GetHostRepositoryIssuesParams defines parameters for GetHostRepositoryIssues.
type GetHostRepositoryIssuesParams struct {
	// Page pagination page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of records to return
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// CreatedAfter filter by created_at after given time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// UpdatedAfter filter by updated_at after given time
	UpdatedAfter *time.Time `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// Sort field to order results by
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order direction to order results by
	Order *string `form:"order,omitempty" json:"order,omitempty"`

	// PullRequest filter by if it's a pull request
	PullRequest *bool `form:"pull_request,omitempty" json:"pull_request,omitempty"`

	// State filter by issue state (open, closed)
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Label filter by label name
	Label *string `form:"label,omitempty" json:"label,omitempty"`
}

// CreateJobJSONBody defines parameters for CreateJob.
type CreateJobJSONBody struct {
	// Url URL of the repository to sync issues from
	Url string `json:"url"`
}

// RepositoriesLookupParams defines parameters for RepositoriesLookup.
type RepositoriesLookupParams struct {
	// Url The URL of the repository to lookup
	Url string `form:"url" json:"url"`
}

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody CreateJobJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetRegistries request
	GetRegistries(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHost request
	GetHost(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostAuthors request
	GetHostAuthors(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostAuthor request
	GetHostAuthor(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwners request
	GetHostOwners(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwner request
	GetHostOwner(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostOwnerMaintainers request
	GetHostOwnerMaintainers(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositories request
	GetHostRepositories(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepository request
	GetHostRepository(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryIssues request
	GetHostRepositoryIssues(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryIssue request
	GetHostRepositoryIssue(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostRepositoryLabels request
	GetHostRepositoryLabels(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJobWithBody request with any body
	CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob request
	GetJob(ctx context.Context, jobId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RepositoriesLookup request
	RepositoriesLookup(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetRegistries(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRegistriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHost(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRequest(c.Server, hostName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostAuthors(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostAuthorsRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostAuthor(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostAuthorRequest(c.Server, hostName, authorName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostOwners(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnersRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostOwner(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnerRequest(c.Server, hostName, ownerName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostOwnerMaintainers(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostOwnerMaintainersRequest(c.Server, hostName, ownerName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostRepositories(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoriesRequest(c.Server, hostName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostRepository(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryRequest(c.Server, hostName, repoName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostRepositoryIssues(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryIssuesRequest(c.Server, hostName, repoName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostRepositoryIssue(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryIssueRequest(c.Server, hostName, repoName, issueNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostRepositoryLabels(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostRepositoryLabelsRequest(c.Server, hostName, repoName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJob(ctx context.Context, jobId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RepositoriesLookup(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRepositoriesLookupRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRegistriesRequest generates requests for GetRegistries
func NewGetRegistriesRequest(server string, params *GetRegistriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRequest generates requests for GetHost
func NewGetHostRequest(server string, hostName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostAuthorsRequest generates requests for GetHostAuthors
func NewGetHostAuthorsRequest(server string, hostName string, params *GetHostAuthorsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/authors", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostAuthorRequest generates requests for GetHostAuthor
func NewGetHostAuthorRequest(server string, hostName string, authorName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "authorName", runtime.ParamLocationPath, authorName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/authors/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnersRequest generates requests for GetHostOwners
func NewGetHostOwnersRequest(server string, hostName string, params *GetHostOwnersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnerRequest generates requests for GetHostOwner
func NewGetHostOwnerRequest(server string, hostName string, ownerName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "ownerName", runtime.ParamLocationPath, ownerName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostOwnerMaintainersRequest generates requests for GetHostOwnerMaintainers
func NewGetHostOwnerMaintainersRequest(server string, hostName string, ownerName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "ownerName", runtime.ParamLocationPath, ownerName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/owners/%s/maintainers", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoriesRequest generates requests for GetHostRepositories
func NewGetHostRepositoriesRequest(server string, hostName string, params *GetHostRepositoriesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created_after", runtime.ParamLocationQuery, *params.CreatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "updated_after", runtime.ParamLocationQuery, *params.UpdatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryRequest generates requests for GetHostRepository
func NewGetHostRepositoryRequest(server string, hostName string, repoName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repoName", runtime.ParamLocationPath, repoName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryIssuesRequest generates requests for GetHostRepositoryIssues
func NewGetHostRepositoryIssuesRequest(server string, hostName string, repoName string, params *GetHostRepositoryIssuesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repoName", runtime.ParamLocationPath, repoName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/issues", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "per_page", runtime.ParamLocationQuery, *params.PerPage); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created_after", runtime.ParamLocationQuery, *params.CreatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UpdatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "updated_after", runtime.ParamLocationQuery, *params.UpdatedAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PullRequest != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pull_request", runtime.ParamLocationQuery, *params.PullRequest); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Label != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "label", runtime.ParamLocationQuery, *params.Label); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryIssueRequest generates requests for GetHostRepositoryIssue
func NewGetHostRepositoryIssueRequest(server string, hostName string, repoName string, issueNumber int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repoName", runtime.ParamLocationPath, repoName)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "issueNumber", runtime.ParamLocationPath, issueNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/issues/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostRepositoryLabelsRequest generates requests for GetHostRepositoryLabels
func NewGetHostRepositoryLabelsRequest(server string, hostName string, repoName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostName", runtime.ParamLocationPath, hostName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repoName", runtime.ParamLocationPath, repoName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/repositories/%s/labels", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateJobRequest calls the generic CreateJob builder with application/json body
func NewCreateJobRequest(server string, body CreateJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateJobRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateJobRequestWithBody generates requests for CreateJob with any type of body
func NewCreateJobRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, jobId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRepositoriesLookupRequest generates requests for RepositoriesLookup
func NewRepositoriesLookupRequest(server string, params *RepositoriesLookupParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repositories/lookup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "url", runtime.ParamLocationQuery, params.Url); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetRegistriesWithResponse request
	GetRegistriesWithResponse(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*GetRegistriesResponse, error)

	// GetHostWithResponse request
	GetHostWithResponse(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*GetHostResponse, error)

	// GetHostAuthorsWithResponse request
	GetHostAuthorsWithResponse(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*GetHostAuthorsResponse, error)

	// GetHostAuthorWithResponse request
	GetHostAuthorWithResponse(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*GetHostAuthorResponse, error)

	// GetHostOwnersWithResponse request
	GetHostOwnersWithResponse(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*GetHostOwnersResponse, error)

	// GetHostOwnerWithResponse request
	GetHostOwnerWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerResponse, error)

	// GetHostOwnerMaintainersWithResponse request
	GetHostOwnerMaintainersWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerMaintainersResponse, error)

	// GetHostRepositoriesWithResponse request
	GetHostRepositoriesWithResponse(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoriesResponse, error)

	// GetHostRepositoryWithResponse request
	GetHostRepositoryWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryResponse, error)

	// GetHostRepositoryIssuesWithResponse request
	GetHostRepositoryIssuesWithResponse(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssuesResponse, error)

	// GetHostRepositoryIssueWithResponse request
	GetHostRepositoryIssueWithResponse(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssueResponse, error)

	// GetHostRepositoryLabelsWithResponse request
	GetHostRepositoryLabelsWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryLabelsResponse, error)

	// CreateJobWithBodyWithResponse request with any body
	CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, jobId int, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// RepositoriesLookupWithResponse request
	RepositoriesLookupWithResponse(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*RepositoriesLookupResponse, error)
}

type GetRegistriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Host
}

// Status returns HTTPResponse.Status
func (r GetRegistriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRegistriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Host
}

// Status returns HTTPResponse.Status
func (r GetHostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostAuthorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]AuthorSummary
}

// Status returns HTTPResponse.Status
func (r GetHostAuthorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostAuthorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostAuthorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Author
}

// Status returns HTTPResponse.Status
func (r GetHostAuthorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostAuthorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostOwnersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]OwnerSummary
}

// Status returns HTTPResponse.Status
func (r GetHostOwnersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostOwnerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Owner
}

// Status returns HTTPResponse.Status
func (r GetHostOwnerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostOwnerMaintainersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Maintainers
}

// Status returns HTTPResponse.Status
func (r GetHostOwnerMaintainersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostOwnerMaintainersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostRepositoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Repository
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostRepositoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Repository
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostRepositoryIssuesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Issue
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryIssuesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryIssuesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostRepositoryIssueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Issue
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryIssueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryIssueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostRepositoryLabelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]LabelCount
}

// Status returns HTTPResponse.Status
func (r GetHostRepositoryLabelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostRepositoryLabelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *struct {
		Details *[]string `json:"details,omitempty"`
		Title   *string   `json:"title,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Job
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RepositoriesLookupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Repository
}

// Status returns HTTPResponse.Status
func (r RepositoriesLookupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RepositoriesLookupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetRegistriesWithResponse request returning *GetRegistriesResponse
func (c *ClientWithResponses) GetRegistriesWithResponse(ctx context.Context, params *GetRegistriesParams, reqEditors ...RequestEditorFn) (*GetRegistriesResponse, error) {
	rsp, err := c.GetRegistries(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRegistriesResponse(rsp)
}

// GetHostWithResponse request returning *GetHostResponse
func (c *ClientWithResponses) GetHostWithResponse(ctx context.Context, hostName string, reqEditors ...RequestEditorFn) (*GetHostResponse, error) {
	rsp, err := c.GetHost(ctx, hostName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostResponse(rsp)
}

// GetHostAuthorsWithResponse request returning *GetHostAuthorsResponse
func (c *ClientWithResponses) GetHostAuthorsWithResponse(ctx context.Context, hostName string, params *GetHostAuthorsParams, reqEditors ...RequestEditorFn) (*GetHostAuthorsResponse, error) {
	rsp, err := c.GetHostAuthors(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostAuthorsResponse(rsp)
}

// GetHostAuthorWithResponse request returning *GetHostAuthorResponse
func (c *ClientWithResponses) GetHostAuthorWithResponse(ctx context.Context, hostName string, authorName string, reqEditors ...RequestEditorFn) (*GetHostAuthorResponse, error) {
	rsp, err := c.GetHostAuthor(ctx, hostName, authorName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostAuthorResponse(rsp)
}

// GetHostOwnersWithResponse request returning *GetHostOwnersResponse
func (c *ClientWithResponses) GetHostOwnersWithResponse(ctx context.Context, hostName string, params *GetHostOwnersParams, reqEditors ...RequestEditorFn) (*GetHostOwnersResponse, error) {
	rsp, err := c.GetHostOwners(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnersResponse(rsp)
}

// GetHostOwnerWithResponse request returning *GetHostOwnerResponse
func (c *ClientWithResponses) GetHostOwnerWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerResponse, error) {
	rsp, err := c.GetHostOwner(ctx, hostName, ownerName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnerResponse(rsp)
}

// GetHostOwnerMaintainersWithResponse request returning *GetHostOwnerMaintainersResponse
func (c *ClientWithResponses) GetHostOwnerMaintainersWithResponse(ctx context.Context, hostName string, ownerName string, reqEditors ...RequestEditorFn) (*GetHostOwnerMaintainersResponse, error) {
	rsp, err := c.GetHostOwnerMaintainers(ctx, hostName, ownerName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostOwnerMaintainersResponse(rsp)
}

// GetHostRepositoriesWithResponse request returning *GetHostRepositoriesResponse
func (c *ClientWithResponses) GetHostRepositoriesWithResponse(ctx context.Context, hostName string, params *GetHostRepositoriesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoriesResponse, error) {
	rsp, err := c.GetHostRepositories(ctx, hostName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoriesResponse(rsp)
}

// GetHostRepositoryWithResponse request returning *GetHostRepositoryResponse
func (c *ClientWithResponses) GetHostRepositoryWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryResponse, error) {
	rsp, err := c.GetHostRepository(ctx, hostName, repoName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryResponse(rsp)
}

// GetHostRepositoryIssuesWithResponse request returning *GetHostRepositoryIssuesResponse
func (c *ClientWithResponses) GetHostRepositoryIssuesWithResponse(ctx context.Context, hostName string, repoName string, params *GetHostRepositoryIssuesParams, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssuesResponse, error) {
	rsp, err := c.GetHostRepositoryIssues(ctx, hostName, repoName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryIssuesResponse(rsp)
}

// GetHostRepositoryIssueWithResponse request returning *GetHostRepositoryIssueResponse
func (c *ClientWithResponses) GetHostRepositoryIssueWithResponse(ctx context.Context, hostName string, repoName string, issueNumber int, reqEditors ...RequestEditorFn) (*GetHostRepositoryIssueResponse, error) {
	rsp, err := c.GetHostRepositoryIssue(ctx, hostName, repoName, issueNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryIssueResponse(rsp)
}

// GetHostRepositoryLabelsWithResponse request returning *GetHostRepositoryLabelsResponse
func (c *ClientWithResponses) GetHostRepositoryLabelsWithResponse(ctx context.Context, hostName string, repoName string, reqEditors ...RequestEditorFn) (*GetHostRepositoryLabelsResponse, error) {
	rsp, err := c.GetHostRepositoryLabels(ctx, hostName, repoName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostRepositoryLabelsResponse(rsp)
}

// CreateJobWithBodyWithResponse request with arbitrary body returning *CreateJobResponse
func (c *ClientWithResponses) CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJobWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

func (c *ClientWithResponses) CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJob(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

// GetJobWithResponse request returning *GetJobResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobId int, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// RepositoriesLookupWithResponse request returning *RepositoriesLookupResponse
func (c *ClientWithResponses) RepositoriesLookupWithResponse(ctx context.Context, params *RepositoriesLookupParams, reqEditors ...RequestEditorFn) (*RepositoriesLookupResponse, error) {
	rsp, err := c.RepositoriesLookup(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRepositoriesLookupResponse(rsp)
}

// ParseGetRegistriesResponse parses an HTTP response from a GetRegistriesWithResponse call
func ParseGetRegistriesResponse(rsp *http.Response) (*GetRegistriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRegistriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Host
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostResponse parses an HTTP response from a GetHostWithResponse call
func ParseGetHostResponse(rsp *http.Response) (*GetHostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Host
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostAuthorsResponse parses an HTTP response from a GetHostAuthorsWithResponse call
func ParseGetHostAuthorsResponse(rsp *http.Response) (*GetHostAuthorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostAuthorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AuthorSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostAuthorResponse parses an HTTP response from a GetHostAuthorWithResponse call
func ParseGetHostAuthorResponse(rsp *http.Response) (*GetHostAuthorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostAuthorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Author
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnersResponse parses an HTTP response from a GetHostOwnersWithResponse call
func ParseGetHostOwnersResponse(rsp *http.Response) (*GetHostOwnersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []OwnerSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnerResponse parses an HTTP response from a GetHostOwnerWithResponse call
func ParseGetHostOwnerResponse(rsp *http.Response) (*GetHostOwnerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Owner
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostOwnerMaintainersResponse parses an HTTP response from a GetHostOwnerMaintainersWithResponse call
func ParseGetHostOwnerMaintainersResponse(rsp *http.Response) (*GetHostOwnerMaintainersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostOwnerMaintainersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Maintainers
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoriesResponse parses an HTTP response from a GetHostRepositoriesWithResponse call
func ParseGetHostRepositoriesResponse(rsp *http.Response) (*GetHostRepositoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryResponse parses an HTTP response from a GetHostRepositoryWithResponse call
func ParseGetHostRepositoryResponse(rsp *http.Response) (*GetHostRepositoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryIssuesResponse parses an HTTP response from a GetHostRepositoryIssuesWithResponse call
func ParseGetHostRepositoryIssuesResponse(rsp *http.Response) (*GetHostRepositoryIssuesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryIssuesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Issue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryIssueResponse parses an HTTP response from a GetHostRepositoryIssueWithResponse call
func ParseGetHostRepositoryIssueResponse(rsp *http.Response) (*GetHostRepositoryIssueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryIssueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Issue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHostRepositoryLabelsResponse parses an HTTP response from a GetHostRepositoryLabelsWithResponse call
func ParseGetHostRepositoryLabelsResponse(rsp *http.Response) (*GetHostRepositoryLabelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostRepositoryLabelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []LabelCount
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateJobResponse parses an HTTP response from a CreateJobWithResponse call
func ParseCreateJobResponse(rsp *http.Response) (*CreateJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *[]string `json:"details,omitempty"`
			Title   *string   `json:"title,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRepositoriesLookupResponse parses an HTTP response from a RepositoriesLookupWithResponse call
func ParseRepositoriesLookupResponse(rsp *http.Response) (*RepositoriesLookupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RepositoriesLookupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
