# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.8.0/configuration-schema.json
package: packages
output: packages.go
generate:
  models: true
  client: true
output-options:
  skip-response-body-getters: true
